

---

- name: Configuring VM for deploying flask app
  hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Installing postgresql on server
    apt:
     name: postgresql
     state: latest
  - name: Configuuring postgresql
    postgresql_db:
     login_user: chinwenducecilia1
     login_password: password
     name: flask
